### ISSUE TITLE
fai schifo ma con amore <3

### ISSUE THREAD

**Issue by NyaomiDEV** [Mamiglia/Requester-Bot#1]
ps: python sh**t

:heart: :heart: :heart: :heart: :heart: :heart:

**Comment by Mamiglia** [comment]
sed s/python/php

comuque questa é la mia prima issue su github <3

**Comment by ghost** [comment]
fai skifo @Mamiglia hihihihihi xdxdxdxd

**Comment by Mamiglia** [comment]
hihihihihihi ne riparliamo quando fai un progetto vero e tuo con un linguaggio di programmazione hihihihih

**Comment by ghost** [comment]
grrr >:(>:(>:(

**Comment by NyaomiDEV** [comment]
HAHA NORMIEZ
